a = [{'title': 'Gravitas: Military coup in Myanmar', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'Gravitas: The military takeover in Myanmar | Where does India stand?', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'No end in sight to the bloody turmoil in Myanmar | Latest English News | World News | WION', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'State of affairs in Myanmar: Military coup seizes power, ousts civilian government | English news', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': "Gravitas: Myanmar's coup is becoming India's problem", 'channel': {'channel_name': 
        'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'Gravitas Live With Palki Sharma Upadhyay | Is there a Chinese hand behind the coup in Myanmar?', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': "Gravitas: Is China backing Myanmar's generals?", 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': '1,200 people reportedly killed in Myanmar coup | Latest English News | WION', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'Gravitas: 5 videos that tell the story of Myanmar after the coup', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'Gravitas Live With Palki Sharma Upadhyay | India and the Myanmar coup | WION Live', 'channel': {'channel_name': 'WION', 
        'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': "Myanmar's shadow government calls for revolt against military coup| Latest English News | WION World", 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'Gravitas: Is Myanmar becoming a security nightmare?', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'Malaysia asks ASEAN to rethink non-interference policy for Myanmar | WION English News', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'How This Myanmar Model Escaped From Military Coup | Stay Curious #38', 'channel': {'channel_name': 'Asian Boss', 'channel_link': 'https://www.youtube.com/user/askasianboss'}}, {'title': 
        'Min Aung Hlaing blames opposition for violence after ASEAN snub', 'channel': {'channel_name': 'Al Jazeera English', 'channel_link': 'https://www.youtube.com/user/AlJazeeraEnglish'}}, {'title': 'Gravitas Plus: The Supply chain crisis', 'channel': {'channel_name': 'WION', 'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'Myanmar coup: What led to the military seizing power? - BBC News', 'channel': {'channel_name': 'BBC News', 'channel_link': 'https://www.youtube.com/user/bbcnews'}}, {'title': '100 days on from the coup in Myanmar - BBC News', 'channel': {'channel_name': 'BBC News', 'channel_link': 'https://www.youtube.com/user/bbcnews'}}, {'title': 'Myanmar Coup : म्यांमार में क्या हुआ, क्यों हुआ और भारत पर इसका क्या असर होगा? \u200c(BBC Hindi)', 'channel': {'channel_name': 'BBC News Hindi', 'channel_link': 'https://www.youtube.com/user/bbchindi'}}, {'title': 'Myanmar Coup: two major cities put under curfew - BBC News', 'channel': {'channel_name': 'BBC News', 'channel_link': 'https://www.youtube.com/user/bbcnews'}}, {'title': 'Myanmar coup: Facebook blocks military-run news site - BBC News', 'channel': {'channel_name': 'BBC News', 'channel_link': 'https://www.youtube.com/user/bbcnews'}}, {'title': 'Myanmar fitness instructor accidentally captures coup unfolding - BBC News', 'channel': 
        {'channel_name': 'BBC News', 'channel_link': 'https://www.youtube.com/user/bbcnews'}}, {'title': 'Roads blocked in Yangon as thousands protest Myanmar coup - BBC News', 'channel': {'channel_name': 'BBC News', 'channel_link': 'https://www.youtube.com/user/bbcnews'}}, {'title': 'Thousands in Myanmar pay respects to teenager shot dead during military coup - BBC News', 'channel': {'channel_name': 'BBC News', 'channel_link': 'https://www.youtube.com/user/bbcnews'}}, {'title': "The monks divided over Myanmar's coup - BBC News", 'channel': {'channel_name': 'BBC News', 'channel_link': 'https://www.youtube.com/user/bbcnews'}}, {'title': 'Myanmar army clashes with anti-coup militia – BBC News', 'channel': {'channel_name': 'BBC News', 'channel_link': 'https://www.youtube.com/user/bbcnews'}}, {'title': 'What can be done about the military coup in Myanmar?', 'channel': {'channel_name': 'euronews', 'channel_link': 'https://www.youtube.com/user/Euronews'}}, {'title': 'Myanmar leader Aung San Suu Kyi detained in military coup | DW News', 'channel': {'channel_name': 'DW News', 'channel_link': 'https://www.youtube.com/user/deutschewelleenglish'}}, {'title': 'Myanmar coup: Military takes control after detaining Aung San Suu Kyi', 'channel': {'channel_name': 'euronews', 'channel_link': 'https://www.youtube.com/user/Euronews'}}, {'title': 'Thousands defy military in Myanmar to continue protests against the coup', 'channel': {'channel_name': 'euronews', 
        'channel_link': 'https://www.youtube.com/user/Euronews'}}, {'title': 'Tensions high as protests against the coup in Myanmar enter second week', 'channel': {'channel_name': 'euronews', 'channel_link': 'https://www.youtube.com/user/Euronews'}}, {'title': "How did European leaders react to Myanmar's military coup?", 'channel': {'channel_name': 'euronews', 'channel_link': 'https://www.youtube.com/user/Euronews'}}, {'title': 'More than 500 protesters killed since military coup in Myanmar | Aung San Suu Kyi | English News', 'channel': {'channel_name': 'WION', 
        'channel_link': 'https://www.youtube.com/channel/UC_gUM8rL-Lrg6O3adPW9K1g'}}, {'title': 'Military coup in Myanmar as elected leader Aung San Suu Kyi is detained', 'channel': {'channel_name': 'FRANCE 24 English', 'channel_link': 'https://www.youtube.com/user/france24english'}}, {'title': 'Myanmar generals rule out envoy visit until ‘stability’ established', 'channel': {'channel_name': 'euronews', 'channel_link': 'https://www.youtube.com/user/Euronews'}}, {'title': 'Myanmar blocks Facebook amid growing resistance to coup', 'channel': {'channel_name': 'euronews', 'channel_link': 'https://www.youtube.com/user/Euronews'}}, {'title': "Myanmar anti-coup protesters launch 'Easter egg strike'", 'channel': {'channel_name': 'euronews', 'channel_link': 'https://www.youtube.com/user/Euronews'}}]
j= 0
while j<len(a):
            ch = a[j]['channel']['channel_name']
            print(ch)
            if ch == 'WION' or ch == 'BBC News' or ch == 'euronews':
                if ch == "BBC News":
                    temp = a[j]['title'].split()
                    temp = " ".join(temp[:-3])
                    a[j]['title'] = temp
            else:
                a.pop(j)
                j = j-1
            
            j = j+1
            print(len(a))
print(a[0])