# Generated by Django 3.2.8 on 2021-10-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=200, verbose_name='Sentence')),
                ('label', models.CharField(max_length=1, verbose_name='Label')),
            ],
        ),
        migrations.DeleteModel(
            name='news_cat',
        ),
    ]
