# Generated by Django 3.2.8 on 2021-10-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20211023_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='newslearnbbc',
            fields=[
                ('sent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='playground.newcat')),
                ('title1', models.CharField(max_length=200, verbose_name='title1')),
                ('title2', models.CharField(max_length=200, verbose_name='title2')),
                ('title3', models.CharField(max_length=200, verbose_name='title3')),
                ('title4', models.CharField(max_length=200, verbose_name='title4')),
                ('title5', models.CharField(max_length=200, verbose_name='title5')),
            ],
        ),
        migrations.CreateModel(
            name='newslearneuronews',
            fields=[
                ('sent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='playground.newcat')),
                ('title1', models.CharField(max_length=200, verbose_name='title1')),
                ('title2', models.CharField(max_length=200, verbose_name='title2')),
                ('title3', models.CharField(max_length=200, verbose_name='title3')),
                ('title4', models.CharField(max_length=200, verbose_name='title4')),
                ('title5', models.CharField(max_length=200, verbose_name='title5')),
            ],
        ),
        migrations.CreateModel(
            name='newslearnwion',
            fields=[
                ('sent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='playground.newcat')),
                ('title1', models.CharField(max_length=200, verbose_name='title1')),
                ('title2', models.CharField(max_length=200, verbose_name='title2')),
                ('title3', models.CharField(max_length=200, verbose_name='title3')),
                ('title4', models.CharField(max_length=200, verbose_name='title4')),
                ('title5', models.CharField(max_length=200, verbose_name='title5')),
            ],
        ),
    ]
