# Generated by Django 3.2.8 on 2021-10-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_newslearnbbc_newslearneuronews_newslearnwion'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslearnbbc',
            name='link1',
            field=models.CharField(max_length=500, null=True, verbose_name='link1'),
        ),
        migrations.AddField(
            model_name='newslearnbbc',
            name='link2',
            field=models.CharField(max_length=500, null=True, verbose_name='link2'),
        ),
        migrations.AddField(
            model_name='newslearnbbc',
            name='link3',
            field=models.CharField(max_length=500, null=True, verbose_name='link3'),
        ),
        migrations.AddField(
            model_name='newslearnbbc',
            name='link4',
            field=models.CharField(max_length=500, null=True, verbose_name='link4'),
        ),
        migrations.AddField(
            model_name='newslearnbbc',
            name='link5',
            field=models.CharField(max_length=500, null=True, verbose_name='link5'),
        ),
        migrations.AddField(
            model_name='newslearneuronews',
            name='link1',
            field=models.CharField(max_length=500, null=True, verbose_name='link1'),
        ),
        migrations.AddField(
            model_name='newslearneuronews',
            name='link2',
            field=models.CharField(max_length=500, null=True, verbose_name='link2'),
        ),
        migrations.AddField(
            model_name='newslearneuronews',
            name='link3',
            field=models.CharField(max_length=500, null=True, verbose_name='link3'),
        ),
        migrations.AddField(
            model_name='newslearneuronews',
            name='link4',
            field=models.CharField(max_length=500, null=True, verbose_name='link4'),
        ),
        migrations.AddField(
            model_name='newslearneuronews',
            name='link5',
            field=models.CharField(max_length=500, null=True, verbose_name='link5'),
        ),
        migrations.AddField(
            model_name='newslearnwion',
            name='link1',
            field=models.CharField(max_length=500, null=True, verbose_name='link1'),
        ),
        migrations.AddField(
            model_name='newslearnwion',
            name='link2',
            field=models.CharField(max_length=500, null=True, verbose_name='link2'),
        ),
        migrations.AddField(
            model_name='newslearnwion',
            name='link3',
            field=models.CharField(max_length=500, null=True, verbose_name='link3'),
        ),
        migrations.AddField(
            model_name='newslearnwion',
            name='link4',
            field=models.CharField(max_length=500, null=True, verbose_name='link4'),
        ),
        migrations.AddField(
            model_name='newslearnwion',
            name='link5',
            field=models.CharField(max_length=500, null=True, verbose_name='link5'),
        ),
    ]
