# Generated by Django 3.2.8 on 2021-10-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_auto_20211023_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslearnbbc',
            name='sent',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='sentence'),
        ),
        migrations.AlterField(
            model_name='newslearneuronews',
            name='sent',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='sentence'),
        ),
        migrations.AlterField(
            model_name='newslearnwion',
            name='sent',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='sentence'),
        ),
    ]
