# Generated by Django 3.2.8 on 2021-10-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_auto_20211024_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.CharField(max_length=300, verbose_name='sentence')),
                ('consider', models.CharField(max_length=1, verbose_name='Consider')),
            ],
        ),
        migrations.RemoveField(
            model_name='newslearnbbc',
            name='link4',
        ),
        migrations.RemoveField(
            model_name='newslearnbbc',
            name='link5',
        ),
        migrations.RemoveField(
            model_name='newslearnbbc',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='newslearnbbc',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='newslearneuronews',
            name='link4',
        ),
        migrations.RemoveField(
            model_name='newslearneuronews',
            name='link5',
        ),
        migrations.RemoveField(
            model_name='newslearneuronews',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='newslearneuronews',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='newslearnwion',
            name='link4',
        ),
        migrations.RemoveField(
            model_name='newslearnwion',
            name='link5',
        ),
        migrations.RemoveField(
            model_name='newslearnwion',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='newslearnwion',
            name='title5',
        ),
    ]
