# Generated by Django 3.2.8 on 2021-10-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_auto_20211025_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enough',
        ),
        migrations.AddField(
            model_name='newslearnbbc',
            name='link4',
            field=models.CharField(max_length=500, null=True, verbose_name='link4'),
        ),
        migrations.AddField(
            model_name='newslearnbbc',
            name='link5',
            field=models.CharField(max_length=500, null=True, verbose_name='link5'),
        ),
        migrations.AddField(
            model_name='newslearnbbc',
            name='title4',
            field=models.CharField(max_length=200, null=True, verbose_name='title4'),
        ),
        migrations.AddField(
            model_name='newslearnbbc',
            name='title5',
            field=models.CharField(max_length=200, null=True, verbose_name='title5'),
        ),
        migrations.AddField(
            model_name='newslearneuronews',
            name='link4',
            field=models.CharField(max_length=500, null=True, verbose_name='link4'),
        ),
        migrations.AddField(
            model_name='newslearneuronews',
            name='link5',
            field=models.CharField(max_length=500, null=True, verbose_name='link5'),
        ),
        migrations.AddField(
            model_name='newslearneuronews',
            name='title4',
            field=models.CharField(max_length=200, null=True, verbose_name='title4'),
        ),
        migrations.AddField(
            model_name='newslearneuronews',
            name='title5',
            field=models.CharField(max_length=200, null=True, verbose_name='title5'),
        ),
        migrations.AddField(
            model_name='newslearnwion',
            name='link4',
            field=models.CharField(max_length=500, null=True, verbose_name='link4'),
        ),
        migrations.AddField(
            model_name='newslearnwion',
            name='link5',
            field=models.CharField(max_length=500, null=True, verbose_name='link5'),
        ),
        migrations.AddField(
            model_name='newslearnwion',
            name='title4',
            field=models.CharField(max_length=200, null=True, verbose_name='title4'),
        ),
        migrations.AddField(
            model_name='newslearnwion',
            name='title5',
            field=models.CharField(max_length=200, null=True, verbose_name='title5'),
        ),
    ]
